### ISSUE TITLE
Generar estadísticas y visualizacion

### ISSUE THREAD

**Issue by Katherine-Ortiz** [jovillarrealm/Medetrics#11]
- [x] Buscar implementación de estadísticas.
- [x] implementar graficas o tableros con estadísticas.
- [x] Analizar posibilidad de entrenar robot para estadísticas.

**Comment by jovillarrealm** [comment]
Propuesta del profesor


- [x] Usar las librerías para analítica y plotting
    - [x] pandas 
    - [x] statsmodels
    - [x] matplotlib
    - [x] seaborn

- [x] Estadísticas como
    - [x] Scatterplots de edades y enfermedades (expandir)
    - [x] mostrar prevalencia de enfermedades por edad.
 

- [x] Quedó en que va a contactar a la gente de ONE Health para ver si podíamos tener ML para ver correlaciones entre edades y enfermedades, de pronto prediccion.
