### ISSUE TITLE
Conexiones bases de datos

### ISSUE THREAD

**Issue by Katherine-Ortiz** [jovillarrealm/Medetrics#13]
- [x] Concluir bases de datos abiertas externas que serán usadas
- [x] conectar bases de datos externas a la base de datos en mongo
- [x] visualizar los datos de las BD externas en la página de visualización

**Comment by jovillarrealm** [comment]
En lo que se refiere a histogramas tenemos como 3 o 4 por cada una de las 5 enfermedades en una plataforma de banco de datos y tenemos otros en la otra plataforma
